name: CI

on: 'push'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build Docker Image'
        run: |
          DOCKER_BUILDKIT=1 docker build . --tag ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/smartcampus-gamification:$GITHUB_SHA --tag ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/smartcampus-gamification:latest
          docker push ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/smartcampus-gamification:$GITHUB_SHA
          docker push ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/smartcampus-gamification:latest
